services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
