services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  worker:
    build: .
    command: celery -A CreditFlow worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
