# Generated by Django 5.1.3 on 2024-11-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_payment', models.IntegerField()),
                ('emis_paid_on_time', models.IntegerField()),
                ('approval_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_customer', to='customer.customer')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
